//! `cargo xtask rive-defs <schema-dir>`: generate `crates/rive/src/defs.rs` (the Rive object
//! model's property keys, field types and type keys) from a dump of the Rive CLI's
//! `rive schema <Type> --json` output, one `<Type>.json` per type (`fixtures/rive/dump-schema.sh`).

use std::collections::BTreeMap;
use std::fmt::Write as _;
use std::path::Path;

use serde_json::Value;

/// How a property's value is stored in a `.riv` file.
fn field_of(ty: &str) -> &'static str {
    match ty {
        "double" => "Float",
        "String" => "String",
        "Bytes" | "List<Id>" => "Bytes",
        "Color" => "Color",
        // uint, uint8, uint16, uint64, int, int16, Id, bool, callback: LEB128 varuint.
        _ => "Uint",
    }
}

pub fn run(args: &[&str]) -> Result<(), String> {
    let dir = args.first().ok_or("usage: cargo xtask rive-defs <schema-dir>")?;
    let mut props: BTreeMap<u64, (String, &'static str, String)> = BTreeMap::new();
    let mut types: BTreeMap<u64, (String, bool)> = BTreeMap::new();
    let mut version = String::new();
    let entries = std::fs::read_dir(dir).map_err(|e| format!("{dir}: {e}"))?;
    let mut files: Vec<_> = entries.filter_map(|e| e.ok().map(|e| e.path())).collect();
    files.sort();
    for path in files {
        let name = path.file_name().and_then(|n| n.to_str()).unwrap_or_default().to_string();
        if name == "version.txt" {
            version = std::fs::read_to_string(&path).unwrap_or_default().trim().to_string();
            continue;
        }
        if name.starts_with('_') || !name.ends_with(".json") {
            continue;
        }
        let text = std::fs::read_to_string(&path).map_err(|e| format!("{}: {e}", path.display()))?;
        let Ok(d) = serde_json::from_str::<Value>(&text) else { continue };
        let (Some(ty), Some(key)) = (d["type"].as_str(), d["typeKey"].as_u64()) else { continue };
        let extends: Vec<&str> = d["extends"].as_array().into_iter().flatten().filter_map(Value::as_str).collect();
        // Objects that join their artboard's object list (what `parentId`, `objectId` and
        // `interpolatorId` index): components and keyframe interpolators.
        let in_artboard = ty == "Component" || extends.iter().any(|e| *e == "Component" || *e == "KeyFrameInterpolator");
        types.insert(key, (ty.to_string(), in_artboard));
        for p in d["properties"].as_array().into_iter().flatten() {
            let (Some(pk), Some(pn), Some(pt)) = (p["key"].as_u64(), p["name"].as_str(), p["type"].as_str()) else { continue };
            let owner = p["owner"].as_str().unwrap_or(ty).to_string();
            if let Some((_, f, _)) = props.get(&pk)
                && *f != field_of(pt)
            {
                return Err(format!("property key {pk} has two field types"));
            }
            props.insert(pk, (pn.to_string(), field_of(pt), owner));
        }
    }
    if types.is_empty() {
        return Err(format!("{dir}: no `<Type>.json` schema files"));
    }
    let mut out = String::new();
    let _ = writeln!(out, "//! Generated by `cargo xtask rive-defs` from the Rive CLI's object model dump");
    let _ = writeln!(out, "//! (`rive schema <Type> --json`, {}). Do not edit.", if version.is_empty() { "unknown version" } else { &version });
    let _ = writeln!(out, "\nuse crate::Field;\n");
    let _ = writeln!(out, "/// Property key, name, owning type and field type, sorted by key.");
    let _ = writeln!(out, "pub(crate) static PROPS: &[(u32, &str, &str, Field)] = &[");
    for (k, (n, f, o)) in &props {
        let _ = writeln!(out, "    ({k}, {n:?}, {o:?}, Field::{f}),");
    }
    let _ = writeln!(out, "];\n");
    let _ = writeln!(out, "/// Type key, name and whether objects of the type join their artboard's object list, sorted by key.");
    let _ = writeln!(out, "pub(crate) static TYPES: &[(u32, &str, bool)] = &[");
    for (k, (n, a)) in &types {
        let _ = writeln!(out, "    ({k}, {n:?}, {a}),");
    }
    let _ = writeln!(out, "];");
    let dest = crate::root().join("crates/rive/src/defs.rs");
    std::fs::write(&dest, out).map_err(|e| format!("{}: {e}", dest.display()))?;
    println!("rive-defs: {} properties, {} types → {}", props.len(), types.len(), Path::new(&dest).display());
    Ok(())
}
